// ACTION TYPES
export const CASES_UPDATE_FETCH_SUCCEEDED = 'CASES_UPDATE_FETCH_SUCCEEDED';
export const CASES_UPDATE_FETCH_FAILED = 'CASES_UPDATE_FETCH_FAILED';
export const DAILY_UPDATE_FETCH_SUCCEEDED = 'DAILY_UPDATE_FETCH_SUCCEEDED';
export const DAILY_UPDATE_FETCH_FAILED = 'DAILY_UPDATE_FETCH_FAILED';
export const GET_CASES = 'GET_CASES';
export const GET_DAILY = 'GET_DAILY';
export const SET_ACTIVE_SLIDE = 'SET_ACTIVE_SLIDE';
export const SET_SEARCH = 'SET_SEARCH';
export const UPDATE_SEARCH = 'UPDATE_SEARCH';
export const SET_DATA = 'SET_DATA';
export const SET_FILTERED_DATA = 'SET_FILTERED_DATA';
export const SET_FORCE_LIST_RERENDER = 'SET_FORCE_LIST_RERENDER';
export const SET_CURRENT_LONGITUDE = 'SET_CURRENT_LONGITUDE';
export const SET_CURRENT_LATITUDE = 'SET_CURRENT_LATITUDE';
export const GET_EACH_CASE = 'GET_EACH_CASE';
export const CASE_FETCH_SUCCEEDED = 'CASE_FETCH_SUCCEEDED';
export const CASE_FETCH_FAILED = 'CASE_FETCH_FAILED';
export const GET_COLOMBIA = 'GET_COLOMBIA';
export const FETCH_COLOMBIA_SUCCEEDED = 'FETCH_COLOMBIA_SUCCEEDED';
export const FETCH_COLOMBIA_FAILED = 'FETCH_COLOMBIA_FAILED';

export const SET_CASES = 'SET_CASES';
export const SET_DAILY_UPDATE = 'SET_DAILY_UPDATE';
