export const CASES_UPDATE_FETCH_SUCCEEDED = 'CASES_UPDATE_FETCH_SUCCEEDED';
export const CASES_UPDATE_FETCH_FAILED = 'CASES_UPDATE_FETCH_FAILED';
export const DAILY_UPDATE_FETCH_SUCCEEDED = 'DAILY_UPDATE_FETCH_SUCCEEDED';
export const DAILY_UPDATE_FETCH_FAILED = 'DAILY_UPDATE_FETCH_FAILED';
export const GET_CASES = 'GET_CASES';
export const GET_DAILY = 'GET_DAILY';

export const SET_CASES = 'SET_CASES';
export const SET_DAILY_UPDATE = 'SET_DAILY_UPDATE';
